// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title IJoltAtlasVerifier
 * @notice Interface for Jolt-Atlas SNARK proof verification
 * @dev Verifies zkML proofs generated by the Jolt-Atlas prover
 */
interface IJoltAtlasVerifier {
    /// @notice Verification key for a specific policy type
    struct VerificationKey {
        bytes32 keyHash;
        uint256[] alpha;
        uint256[] beta;
        uint256[] gamma;
        uint256[] delta;
        uint256[][] ic;
    }

    /// @notice Verify a Jolt-Atlas SNARK proof
    /// @param proof The serialized proof data (~48KB)
    /// @param publicInputs The public inputs to the proof
    /// @param policyHash The policy hash this proof is for
    /// @return valid True if the proof is valid
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs,
        bytes32 policyHash
    ) external view returns (bool valid);

    /// @notice Register a verification key for a policy type
    /// @param policyType The type of policy (e.g., "vault-limits", "ltv-bounds")
    /// @param vk The verification key
    function registerVerificationKey(string calldata policyType, VerificationKey calldata vk) external;

    /// @notice Get the verification key for a policy type
    /// @param policyType The type of policy
    /// @return vk The verification key
    function getVerificationKey(string calldata policyType) external view returns (VerificationKey memory vk);

    /// @notice Check if a verification key exists for a policy type
    /// @param policyType The type of policy
    /// @return exists True if the key exists
    function hasVerificationKey(string calldata policyType) external view returns (bool exists);
}
